apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Teeworks1/grafana.git  #
    targetRevision: HEAD
    path: .
    helm: 
      valueFiles:
        - grafana-values.yaml
  destination:
    qaserver: https://kubernetes.default.svc
    namespace: monitoring