# useStatefulSet: true
# headlessService: true
# # adminUser: "admin"
# # adminPassword: "strongpassword"
# admin:
#   existingSecret: grafana
#   userKey: admin
#   passwordKey: admin-password
#   secretName: grafana
# service:
#   enabled: true
#   type: ClusterIP
#   port: 80
#   labels:
#     app: grafana
# ldap:
#   enabled: false
#   existingSecret: ""
# sidecar:
#   dashboards: 
#     enabled: true
#     SCProvider: true
# useConfigMap: true
# createConfigMap: true
# replicas: 1
# adminUser: "admin"
# adminPassword: "strongpassword"
# # admin:
# #   existingSecret: ""
# #   userKey: "admin"
# #   passwordKey: "admin-password"
# #   secretName: "grafana"
# image:
#   repository: grafana/grafana
#   tag: "11.4.0"
#   sha: ""
#   pullPolicy: IfNotPresent
# extraInitContainers: []
# initChownData:
#   enabled: false
# persistence: 
#   enabled: true
#   initChownData: false 
#   securityContext:
#     runAsUser: 0
#   storageClassName: standard
#   type: pvc
#   accessModes:
#     - ReadWriteOnce
#   size: 10Gi
# autoscaling:
#   enabled: true
# # ingress:
# #   enabled: true
# #   className: nginx
# #   annotations:
# #     kubernetes.io/ingress.className: nginx
# #     kubernetes.io/tls-acme: "true"
# #   labels: {}
# #   path: /
# #   pathType: Prefix
# #   hosts:
# #     - chart-example.local
# #   extraPaths: null
# #   tls: 
# #    - secretName: tls-secret
# #      hosts:
# #        - chart-example.local
# # env:
# #   GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: ""
# #   GF_SECURITY_ADMIN_USER: admin
# #   GF_SECURITY_ADMIN_PASSWORD: "admin"
#   #GF_SECURITY_ADMIN_PASSWORD__FILE: ""
# datasources: 
#  datasources.yaml:
#    apiVersion: 1
#    datasources:
#    - name: Prometheus
#      type: prometheus
#      url: http://prometheus-server.monitoring.svc.cluster.local:80
#      access: proxy
#      isDefault: true
#    - name: Loki-ap
#      type: loki
#      url: http://loki-ap.monitoring.svc.cluster.local:3100
#      access: proxy
#      isDefault: false


useStatefulSet: true
headlessService: true
adminUser: admin
adminPassword: strongpassword
service:
  enabled: true
  type: ClusterIP
  port: 80
  labels:
    app: grafana
ldap:
  enabled: false
  existingSecret: ""
sidecar:
  dashboards: 
    enabled: true
    SCProvider: true
useConfigMap: true
createConfigMap: true
replicas: 1
image:
  repository: grafana/grafana
  tag: "12.0.2"
  sha: ""
  pullPolicy: IfNotPresent
extraInitContainers: []
initChownData:
  enabled: false
persistence: 
  enabled: true
  initChownData: false 
  securityContext:
    runAsUser: 0
  storageClassName: standard
  type: pvc
  accessModes:
    - ReadWriteOnce
  size: 10Gi
autoscaling:
  enabled: true
datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local:80
      access: proxy
      isDefault: true
    - name: Loki-ap
      type: loki
      url: http://loki-ap.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
